name: Docker Build and Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set Docker TAG
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: echo ::set-env name=TAG::${GITHUB_REF#refs/tags/v}

    - name: Build and push Docker image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        TAG: ${{ env.TAG }}
      run: |
        echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin
        docker buildx create --use --name mybuilder
        docker buildx build -f docker/Dockerfile --platform linux/amd64 -t ${DOCKERHUB_USERNAME}/scaffold:latest -t ${DOCKERHUB_USERNAME}/scaffold:${{ env.TAG }} --push .

