name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cover:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20.2"
        id: go
      - run: make deps cover
      - uses: codecov/codecov-action@v3.1.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
